from sound import Sound
from animation import Animation
from utility import Utility
from text_color import TextColor
from ascii_animation import play_ascii_animation, load_ascii_art_animation_from_json
from time import sleep

def main():
    Utility.clear_screen()
    # Utility.hide_cursor()
    # dialing_phone_num_text_animation = Animation.animated_text("Dialing phone number", end_text="Complete!\n", static_text_color= TextColor.RAINBOW, animated_text_color= TextColor.RAINBOW, end_text_color= TextColor.RAINBOW, delay_between_chars= 0.2, continue_thread_after_stop_for= 1)
    # Sound.play(Sound.DIAL_TONE, pause= 1)
    # Sound.play(Sound.DIALING_PHONE_NUMBER, pause = 2.4)
    # dialing_phone_num_text_animation.stop(wait_before_continueing_after_thread_stop_for= 1)
    # connect_to_computer_text_animation = Animation.animated_text("Connecting to computer over modem", end_text="Complete!\n", static_text_color= TextColor.random(), animated_text_color= TextColor.random(), end_text_color=TextColor.random(), delay_between_chars= 0.2, continue_thread_after_stop_for= 1)
    # Sound.play(Sound.CONNECTING_TO_COMPUTER_OVER_MODEM_SHORT, pause = 9)
    # connect_to_computer_text_animation.stop(wait_before_continueing_after_thread_stop_for= 1)
    # booting_up_computer_text_animation = Animation.animated_text("Booting up computer", end_text="Complete!\n", delay_between_chars= 0.2, continue_thread_after_stop_for=3)
    # Sound.play(Sound.MAC_OS_STARTUP_MODERN_SOUND, pause= 5)
    # booting_up_computer_text_animation.stop(wait_before_continueing_after_thread_stop_for= 1)
    # print("Computer booted up!")
    # print_animated_message1 = Animation.animated_text(static_text="", animated_text="I can also print animated messages like this one! Depending on how long I hold it for, I can animated it more than once!", end_text="\n", delay_between_chars= 0.02, continue_thread_after_stop_for= 1)
    # print_animated_message1.stop(wait_before_continueing_after_thread_stop_for= 2)
    # print_animated_message2 = Animation.animated_text(static_text="", animated_text="I can print fast,", delay_between_chars= 0.05, continue_thread_after_stop_for= 0.1)
    # print_animated_message2.stop(0.01)
    # print_animated_message3 = Animation.animated_text(static_text="I can print fast,", animated_text=" or I can print slow,", delay_between_chars= 0.2, continue_thread_after_stop_for= 0.1)
    # print_animated_message3.stop(0.01)
    # print_animated_message4 = Animation.animated_text(static_text="I can print fast, or I can print slow,", animated_text=" or I can print very slow!", end_text="\n", delay_between_chars= 0.4, continue_thread_after_stop_for= 1)
    # print_animated_message4.stop(0.01)

    # simpson_bush_animation = load_ascii_art_animation_from_json("animation_images_json/simpson_bush.json")
    # play_ascii_animation(simpson_bush_animation, frames_per_second=12, loop_num_times= -2, continue_thread_after_stop_for= 2)
    # print("Done!")
    # sleep(5)
    # Utility.clear_screen()
    # simpson_bush_animation_playing = play_ascii_animation(simpson_bush_animation, frames_per_second=12, loop_num_times= 0, continue_thread_after_stop_for= 2)
    # sleep(20)
    # simpson_bush_animation_playing.stop(2)
    # print("Done!")
    # Utility.clear_screen()
    # dog1 = load_ascii_art_animation_from_json("image_json/dog1.json")
    # dog2 = load_ascii_art_animation_from_json("image_json/dog2.json")
    # dog3 = load_ascii_art_animation_from_json("image_json/dog3.json")
    # dog4 = load_ascii_art_animation_from_json("image_json/dog4.json")
    # dog5 = load_ascii_art_animation_from_json("image_json/dog5.json")
    # hack_the_planet = load_ascii_art_animation_from_json("image_json/hack_the_planet.json")
    # print()
    # play_ascii_animation(dog1, frames_per_second=1)
    # print()
    # play_ascii_animation(dog2, frames_per_second=1)
    # print()
    # play_ascii_animation(dog3, frames_per_second=1)
    # print()
    # play_ascii_animation(dog4, frames_per_second=1)
    # print()
    # play_ascii_animation(dog5, frames_per_second=1)
    # print()
    # print("Done!")
    # print()
    # play_ascii_animation(hack_the_planet, frames_per_second=1)
    
    Utility.clear_screen()
    Utility.hide_cursor()
    hack_the_planet_animation = load_ascii_art_animation_from_json("animation_images_json/hack_the_planet_animation.json")
    hack_the_planet_thread = play_ascii_animation(hack_the_planet_animation, frames_per_second=24, loop_num_times= 0, continue_thread_after_stop_for= 2)
    hack_the_planet_thread.stop(2)

if __name__ == '__main__':
    main()